# https://github.com/Koihik/LuaFormatter/blob/master/docs/Style-Config.md
align_args: false
align_parameter: false
chop_down_parameter: true
break_after_functiondef_lp: true
break_before_functiondef_rp: true
align_table_field: false
chop_down_table: true
table_sep: ','
extra_sep_at_table_end: true
spaces_inside_table_braces: true
