#!/bin/zsh

# Check for presence of XDG variables
if [[ ! -v XDG_CONFIG_HOME || ! -v XDG_DATA_HOME || ! -v XDG_CACHE_HOME ]]; then
  echo 'XDG directories not set'
  return 1
fi

# Set up history and zsh options
HISTFILE=$XDG_DATA_HOME/zsh/histfile
HISTSIZE=512000
SAVEHIST=256000
bindkey -e
setopt APPEND_HISTORY
# History with timestamps and elapsed time
setopt EXTENDED_HISTORY
setopt INC_APPEND_HISTORY_TIME
# First remove oldest duplicate history items
setopt HIST_EXPIRE_DUPS_FIRST
# Better performance for locking of history file
setopt HIST_FCNTL_LOCK
# Don't add the history item consecutively
setopt HIST_IGNORE_DUPS
# Don't add history items with leading space
setopt HIST_IGNORE_SPACE
# Remove spaces
setopt HIST_REDUCE_BLANKS
# Don't execute history item immediately
setopt HIST_VERIFY
# List jobs with pid
setopt LONG_LIST_JOBS
# Remove no match warning
setopt NONOMATCH
# Move cursor to end of completion
setopt ALWAYS_TO_END
# Attempt completion if mid-word
setopt COMPLETE_IN_WORD
# Allow comments in interactive shell
setopt INTERACTIVE_COMMENTS
# Don't push the same directory consecutively
setopt PUSHD_IGNORE_DUPS

# Set max buffer size zsh-users/zsh-autosuggestions
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
# Use async suggestions
ZSH_AUTOSUGGEST_USE_ASYNC=1

# Configure fzf-z to use `fasd` instead of `z`
FZFZ_RECENT_DIRS_TOOL=fasd
# Configure fzf-z to use `exa -T` instead of the default `tree`
FZFZ_PREVIEW_COMMAND="exa -T {}"
# Configure fzf-z to not deduplicate directory entries
FZFZ_UNIQUIFIER="cat"
# Configure some fzf-z custom directories
FZFZ_EXTRA_DIRS="~/desktop ~/dev ~/documents ~/downloads ~/pictures ~/sounds ~/videos"

# Set up NVM directory
export NVM_DIR="$XDG_CONFIG_HOME/nvm"
# Same effect as `"$NVM_DIR/nvm.sh" --no-use` but for `zsh-nvm`
export NVM_NO_USE=true

# Set up ZINIT array parameters
typeset -A ZINIT
# Where Zinit code resides
ZINIT[BIN_DIR]=$XDG_DATA_HOME/zinit/bin
# Where Zinit should create all working directories
ZINIT[HOME_DIR]=$XDG_DATA_HOME/zinit
# Path to `.zcompdump` file, with the file included
ZINIT[ZCOMPDUMP_PATH]=$XDG_CACHE_HOME/zcompdump
# If set to 1, then Zinit will skip checking if a Turbo-loaded object exists
ZINIT[OPTIMIZE_OUT_DISK_ACCESSES]=1

source $ZINIT[BIN_DIR]/zinit.zsh

# Setup zsh plugins
zinit light-mode for \
  is-snippet \
    ~/dotfiles/scripts/fasd-init-cache.zsh \
    lukechilds/zsh-nvm \
  atload"source ~/.p10k.zsh" nocd \
    romkatv/powerlevel10k \
  atclone"dircolors -b LS_COLORS > lscolors.zsh" \
  atpull"%atclone" pick"lscolors.zsh" nocompile"!" \
    trapd00r/LS_COLORS

zinit wait lucid for \
    zsh-users/zsh-history-substring-search \
    hcgraf/zsh-sudo \
    zdharma/history-search-multi-word \
    andrewferrier/fzf-z \
  atinit"ZINIT[COMPINIT_OPTS]=-C; zicompinit" \
  atload"!_zsh_autosuggest_start" \
    zsh-users/zsh-autosuggestions \
  atinit"zicdreplay" \
    zdharma/fast-syntax-highlighting \
    zlsun/solarized-man \
  blockf atpull"zinit creinstall -q ." \
    zsh-users/zsh-completions

# The following lines were added by compinstall

zstyle ':completion:*' completer _list _expand _complete _ignored _match _approximate _prefix
zstyle ':completion:*' completions 1
zstyle ':completion:*' condition 7
zstyle ':completion:*' expand prefix suffix
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' glob 1
zstyle ':completion:*' ignore-parents parent pwd .. directory
zstyle ':completion:*' insert-unambiguous false
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-prompt '%SAt %p (of %l): Hit TAB for more, or type%s'
zstyle ':completion:*' list-suffixes true
zstyle ':completion:*' matcher-list '' 'm:{[:lower:]}={[:upper:]}' 'r:|[._-/]=** r:|=**' '+m:{[:lower:]}={[:upper:]}'
zstyle ':completion:*' match-original both
zstyle ':completion:*' max-errors 2
zstyle ':completion:*' menu select=1
zstyle ':completion:*' original false
zstyle ':completion:*' preserve-prefix '//[^/]##/'
zstyle ':completion:*' select-prompt '%SAt %l (%p)%s'
zstyle ':completion:*' substitute 1
zstyle ':completion:*' use-compctl true
zstyle ':completion:*' verbose true
zstyle :compinstall filename '/home/animi_vulpis/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

## AnimiVulpis: Use CTRL+(hjkl) besides cursor keys in menu completion
zmodload zsh/complist
bindkey -M menuselect '^h' vi-backward-char        # left
bindkey -M menuselect '^k' vi-up-line-or-history   # up
bindkey -M menuselect '^l' vi-forward-char         # right
bindkey -M menuselect '^j' vi-down-line-or-history # bottom
# # Bind <shift-tab> to go **backwards** in selection list
bindkey -M menuselect '^\[[Z' reverse-menu-complete

# History substring search config
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# Set key-binding https://github.com/zsh-users/zsh-autosuggestions#key-bindings
bindkey '^ ' autosuggest-accept

# Define word jump behaviour
export WORDCHARS=''

# Defining go paths
export GOPATH="$HOME/go"
export GOBIN="$GOPATH/bin"

# PATH modification for cargo/go
export PATH="$HOME/.cargo/bin:$GOBIN:$PATH"

# alias definitions
alias vi="nvim"
alias vim="nvim"
alias ls="ls --color=auto"
alias ll="ls --color=auto -lh"
alias lh="ls --color=auto -lhA"
alias es="exa"
alias el="exa -l --time-style=long-iso"
alias eh="exa -la --time-style=long-iso"
alias et="exa -T"

# More environment variables
export SUDO_EDITOR="nvim"
export EDITOR="nvim"
export VISUAL="code -w"
export LESS="-x4 -Ri"

# broot initialization
source /home/animi_vulpis/.config/broot/launcher/zsh/br
