live_config_reload = false

[window]
dynamic_padding = true
dynamic_title = true

[window.padding]
x = 1
y = 1

[scrolling]
history = 42000

[font]
size = 14.0
builtin_box_drawing = false

[font.normal]
family = "Iosevka Term"

[colors.primary]
foreground = "#dfdccc"
background = "#002b36"
dim_foreground = "#596f74"
bright_foreground = "#b0baba"

[colors.cursor]
text = "#002b36"
cursor = "#dfdccc"

[colors.normal]
black = "#3e575e"
red = "#dc322f"
green = "#859900"
yellow = "#b58900"
blue = "#268bd2"
magenta = "#d33682"
cyan = "#2aa198"
white = "#fdf6e3"

[colors.bright]
black = "#596f74"
red = "#e75d23"
green = "#b1cc00"
yellow = "#ffc105"
blue = "#6cb2e4"
magenta = "#da58bc"
cyan = "#49d0ae"
white = "#fefefe"

[colors.dim]
black = "#0e242a"
red = "#9c3b3a"
green = "#6f7b1e"
yellow = "#8d752a"
blue = "#336c94"
magenta = "#98255c"
cyan = "#29706a"
white = "#fde8af"

[[colors.indexed_colors]]
color = "#6f7b1e"
index = 17

[selection]
save_to_clipboard = true

[[hints.enabled]]
# command = "xdg-open" # On Linux/BSD
command = "open"
hyperlinks = true
post_processing = true
persist = false
mouse = { mods = "Control|Shift", enabled = true }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[keyboard]
bindings = [
    { key = "L", mods = "Control|Shift", action = "ClearHistory" },
    { key = "Slash", mods = "Control", chars = "\u001F" },
]
